04-lection2-02-skeleton
js-tasks-ru/htmlcss-20210916_harvey2009 pull request #7
Opened 2021-09-30 17:17 UTC by luchnikovs

2021-09-30 17:17 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-10-01 07:51 UTC, GSemikozov requested changes

2021-10-01 07:51 UTC, GSemikozov commented on 04-lection2/02-skeleton/index.html
> +          <div class="skeleton__line" style="width: 40%"></div>
вот здесь как раз я бы рекомендовал управлять шириной через модификаторы) например skeleton__line_md или skeleton__line_short и т.д.

2021-10-01 07:51 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  border: 1px solid #ACB5BD;
цвет лучше сразу забрать из переменных

2021-10-01 08:54 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-10-01 08:56 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-10-01 10:38 UTC, GSemikozov approved these changes

2021-10-01 10:38 UTC, merged